//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.10 at 10:58:42 PM CEST 
//


package com.sun.grid.xml.qstat;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 *  
 *                This schema describes most of the qstat outputs. There are extra
 *                schema defintions for "qstat -j" and and "qstat -j job".
 *               
 * 
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="queue_info" type="{}queue_info_t" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="job_info" type="{}job_info_t" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="cluster_queue_summary" type="{}cqueue_summary_t" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "queueInfo",
    "jobInfo",
    "clusterQueueSummary"
})
@XmlRootElement(name = "job_info")
public class JobInfo {

    @XmlElement(name = "queue_info")
    protected List<QueueInfoT> queueInfo;
    @XmlElement(name = "job_info")
    protected List<JobInfoT> jobInfo;
    @XmlElement(name = "cluster_queue_summary")
    protected List<CqueueSummaryT> clusterQueueSummary;

    /**
     * Gets the value of the queueInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the queueInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getQueueInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link QueueInfoT }
     * 
     * 
     */
    public List<QueueInfoT> getQueueInfo() {
        if (queueInfo == null) {
            queueInfo = new ArrayList<QueueInfoT>();
        }
        return this.queueInfo;
    }

    /**
     * Gets the value of the jobInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the jobInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getJobInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JobInfoT }
     * 
     * 
     */
    public List<JobInfoT> getJobInfo() {
        if (jobInfo == null) {
            jobInfo = new ArrayList<JobInfoT>();
        }
        return this.jobInfo;
    }

    /**
     * Gets the value of the clusterQueueSummary property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the clusterQueueSummary property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getClusterQueueSummary().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CqueueSummaryT }
     * 
     * 
     */
    public List<CqueueSummaryT> getClusterQueueSummary() {
        if (clusterQueueSummary == null) {
            clusterQueueSummary = new ArrayList<CqueueSummaryT>();
        }
        return this.clusterQueueSummary;
    }

}
