//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.10 at 10:58:42 PM CEST 
//


package com.sun.grid.xml.qstat;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for queue_list_t complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="queue_list_t">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence minOccurs="0">
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="qtype" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="slots_resv" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
 *         &lt;element name="slots_used" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
 *         &lt;element name="slots_total" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
 *         &lt;element name="load_avg" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="arch" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="state" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="message" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="resource" type="{}resource_t" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="job_list" type="{}job_list_t" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "queue_list_t", propOrder = {
    "name",
    "qtype",
    "slotsResv",
    "slotsUsed",
    "slotsTotal",
    "loadAvg",
    "arch",
    "state",
    "message",
    "resource",
    "jobList"
})
public class QueueListT {

    protected String name;
    protected String qtype;
    @XmlElement(name = "slots_resv")
    @XmlSchemaType(name = "unsignedInt")
    protected Long slotsResv;
    @XmlElement(name = "slots_used")
    @XmlSchemaType(name = "unsignedInt")
    protected Long slotsUsed;
    @XmlElement(name = "slots_total")
    @XmlSchemaType(name = "unsignedInt")
    protected Long slotsTotal;
    @XmlElement(name = "load_avg")
    protected Float loadAvg;
    protected String arch;
    protected String state;
    protected List<String> message;
    protected List<ResourceT> resource;
    @XmlElement(name = "job_list")
    protected List<JobListT> jobList;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the qtype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQtype() {
        return qtype;
    }

    /**
     * Sets the value of the qtype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQtype(String value) {
        this.qtype = value;
    }

    /**
     * Gets the value of the slotsResv property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getSlotsResv() {
        return slotsResv;
    }

    /**
     * Sets the value of the slotsResv property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setSlotsResv(Long value) {
        this.slotsResv = value;
    }

    /**
     * Gets the value of the slotsUsed property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getSlotsUsed() {
        return slotsUsed;
    }

    /**
     * Sets the value of the slotsUsed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setSlotsUsed(Long value) {
        this.slotsUsed = value;
    }

    /**
     * Gets the value of the slotsTotal property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getSlotsTotal() {
        return slotsTotal;
    }

    /**
     * Sets the value of the slotsTotal property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setSlotsTotal(Long value) {
        this.slotsTotal = value;
    }

    /**
     * Gets the value of the loadAvg property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getLoadAvg() {
        return loadAvg;
    }

    /**
     * Sets the value of the loadAvg property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setLoadAvg(Float value) {
        this.loadAvg = value;
    }

    /**
     * Gets the value of the arch property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArch() {
        return arch;
    }

    /**
     * Sets the value of the arch property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArch(String value) {
        this.arch = value;
    }

    /**
     * Gets the value of the state property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setState(String value) {
        this.state = value;
    }

    /**
     * Gets the value of the message property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the message property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMessage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getMessage() {
        if (message == null) {
            message = new ArrayList<String>();
        }
        return this.message;
    }

    /**
     * Gets the value of the resource property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the resource property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getResource().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ResourceT }
     * 
     * 
     */
    public List<ResourceT> getResource() {
        if (resource == null) {
            resource = new ArrayList<ResourceT>();
        }
        return this.resource;
    }

    /**
     * Gets the value of the jobList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the jobList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getJobList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JobListT }
     * 
     * 
     */
    public List<JobListT> getJobList() {
        if (jobList == null) {
            jobList = new ArrayList<JobListT>();
        }
        return this.jobList;
    }

}
