#!/bin/bash

if [ -d filesystem-test-fixture ]
then
	exit 0
fi

mkdir -p $PWD/filesystem-test-fixture/links
echo "Hello World" > $PWD/filesystem-test-fixture/links/file0
touch $PWD/filesystem-test-fixture/links/file1

ln -s $PWD/filesystem-test-fixture/links/file0 $PWD/filesystem-test-fixture/links/link0
ln -s $PWD/filesystem-test-fixture/links/file1 $PWD/filesystem-test-fixture/links/link1
ln -s $PWD/filesystem-test-fixture/links/file2 $PWD/filesystem-test-fixture/links/link2
ln -s $PWD/filesystem-test-fixture/links/link0 $PWD/filesystem-test-fixture/links/link3
ln -s $PWD/filesystem-test-fixture/links/link2 $PWD/filesystem-test-fixture/links/link4
ln -s $PWD/filesystem-test-fixture/links/link6 $PWD/filesystem-test-fixture/links/link5
ln -s $PWD/filesystem-test-fixture/links/link5 $PWD/filesystem-test-fixture/links/link6
